### ISSUE TITLE
FFO Application: https://gamer2810.github.io/steam-miniprofile

### ISSUE THREAD

**Issue by gamer2810** [gridaco/cors.sh#10]
https://gamer2810.github.io/steam-miniprofile/

**Comment by softmarshmallow** [comment]
Hi. you can start using proxy.cors.sh
I don't see your website currently running, so once your site is launched and requires extra quota,  use this thread to let me know.

Thank you :)

**Comment by gamer2810** [comment]
Hello, 
Thank you for replying.

The website is currently running. 
It's just a tool to load Steam's miniprofile to use as an embed so it does not have any extra UI element.

When I made requests to proxy.cors.sh I got error code 429 for TOO_MANY_REQUESTS although I highly doubt this web has 100 requests/hour. Can you help check the request logs on your end?

![image](https://user-images.githubusercontent.com/45266477/192221556-dc47672b-ad66-4e84-b9ff-8de936cb18a6.png) 
![image](https://user-images.githubusercontent.com/45266477/192221023-79ed949d-1ab0-4c9b-b00a-19944043afda.png)

Thank you in advance.

**Comment by gamer2810** [comment]
Also I can't register a project at Grida for some reason.
The create project request tells me that the call to services.cors.sh was blocked by CORS.

![image](https://user-images.githubusercontent.com/45266477/192222735-a29a9bb7-a9df-4658-8cf0-71fa396cbb5b.png)

**Comment by softmarshmallow** [comment]
We are working on the cors.sh website & console.
At this moment you can use the public proxy.cors.sh.

This will be fixed & live within this week.

I'll let you know when this is done. sorry for the inconvenience.

**Comment by gamer2810** [comment]
Proxy is working as of this comment.
Closing this issue.
