### ISSUE TITLE
ramen

### ISSUE THREAD

**Issue by aleganza** [gridaco/cors.sh#100]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project has more than **5 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://github.com/aleganza/ramen

### Expected Quota of usage

It is an app to watch anime for free on mobile, so if I watched 3 episodes each day, in a month I would have consumed 150 requests, but this is very indicative and might require more for its efficiency.

### Details

```markdown
- Category: Streaming Service
- License: GNU General Public License v3.0
- Date of release: Still in development
```

### Anything else?

I'm sorry but I lied about the star count so I could apply for this program, the repo has only 2 stars but I think it may get a little popular. If you will accept this even tho the star count is wrong, thank you.

**Comment by softmarshmallow** [comment]
Hi. sorry to tell you that your application does not meet the minimum requirements.
Please consider uesing our Pro plan.
