### ISSUE TITLE
cors

### ISSUE THREAD

**Issue by Aishwaaya** [gridaco/cors.sh#104]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project has more than **5 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

anonsports.com

### URL to your website

anonsports.com

### Expected Quota of usage

anonsports.com

### Details

```markdown
- Category:
- License:
- Date of release:
```

### Anything else?

anonsports.com

**Comment by Aishwaaya** [comment]
thnx

**Comment by softmarshmallow** [comment]
Hi. Seems like your project is not a Open Source project. Please consider using Pro subscription.
