### ISSUE TITLE
Looker AI Explorer

### ISSUE THREAD

**Issue by rodricksnyc** [gridaco/cors.sh#106]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project has more than **5 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://github.com/bytecodeio/ai-three

### Expected Quota of usage

less than 1K per year

### Details

```markdown
- Category:
- License:
- Date of release:
```

**Comment by softmarshmallow** [comment]
Hi. The link you provided seems unreachable 
Please re-open the issue with a valid public repo url. 
Thank you

**Comment by rodricksnyc** [comment]
Sorry, I had it open but then Slack removed the key. Been having problems
writing from this app to slack without using this cors proxy. Thanks again!
