### ISSUE TITLE
Apple2TS Apple II Emulator

### ISSUE THREAD

**Issue by ct6502** [gridaco/cors.sh#107]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project has more than **5 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://github.com/ct6502/apple2ts

### URL to your website

https://apple2ts.com

### Expected Quota of usage

5 calls per day, 30Mb per call, so 150Mb per day max

### Details

```markdown
- Category: Retro computer emulator
- License: Creative Commons Attribution Share Alike 4.0 International
- Date of release: 12/18/2022
```

### Anything else?

This is an emulator for an Apple II computer. Users can upload their own floppy disk images and start up the emulator. I want to allow users to add a URL to a disk image. For example, they could point the emulator at a floppy disk image on the Internet Archive, and have it load automatically. Unfortunately, most of these sites do not have CORS in the header and so it fails.

Working example (doesn't require a proxy):
https://apple2ts.com/#https://a2desktop.s3.amazonaws.com/A2DeskTop-1.4-alpha4-en_800k.2mg

Failing example:
https://apple2ts.com/#https://github.com/a2-4am/4cade/releases/download/v5.0.1/Total.Replay.hdv

![apple2ts](https://github.com/gridaco/cors.sh/assets/5461379/03d83600-d1d6-44c7-afa1-86795175776e)

**Comment by softmarshmallow** [comment]
What a amazing project you have!
Please send me an email so I can reply you with api key.
=> universe@grida.co

**Comment by ct6502** [comment]
Thanks so much for the API key, and for the kind words about the project!
