### ISSUE TITLE
Request CORS.sh key for dingmark

### ISSUE THREAD

**Issue by alswl** [gridaco/cors.sh#108]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project has more than **5 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://github.com/alswl/dingmark

### URL to your website

https://alswl.github.io/dingmark/

### Expected Quota of usage

Up to 10,000 requests per month.

### Details

```markdown
- Category: IM
- License: Apache-2.0 license
- Date of release: 05/02/2024
```

**Comment by softmarshmallow** [comment]
Hi. Thank you for your application.

can you please send me a email here - universe@grida.co
We'll be sending out api key via email.

Plus, your project seems relatively new, so would it be ok for us to take extra few days for our decision?
It's simply for preventing spam applications, we appricate your understanding.

Thank you !

**Comment by softmarshmallow** [comment]
Thanks I've received your email well. I'm super busy right now, I'll be sending you api key this weekend. sorry about that.
thank you for your patience!

**Comment by softmarshmallow** [comment]
@alswl Hey, just sent you an email. sorry it took so long.

**Comment by alswl** [comment]
@softmarshmallow All good things come to those who wait. Thanks.
