### ISSUE TITLE
ProyectX

### ISSUE THREAD

**Issue by Albertwo512** [gridaco/cors.sh#127]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project has more than **10 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://github.com/Albertwo512/X-B2

### URL to your website

http://localhost:3000/home

### Expected Quota of usage

100 

### Details

```markdown
- Category:
- License:
- Date of release:
```

**Comment by softmarshmallow** [comment]
Hi. sorry to tell you your project does not meet the requirements
