### ISSUE TITLE
playidtv

### ISSUE THREAD

**Issue by Playidtv2** [gridaco/cors.sh#130]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project has more than **10 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

[https://drzl.short.gy/playidtvnew.m3u](url)

### URL to your website

![imagen_editada (3)](https://github.com/gridaco/cors.sh/assets/159120249/71c22697-3f7d-4f03-900e-144264457226)
[https://drzl.short.gy/playidtvnew.m3u](url)

### Expected Quota of usage

https://playidtv24.vercel.app
![20240610_073308](https://github.com/gridaco/cors.sh/assets/159120249/ffb07cfd-1536-4610-b36b-0687dfb995b4)

### Details

```markdown
- Category:
- License:
- Date of release:
```

**Comment by softmarshmallow** [comment]
Hi. This program is only applicable for Open source projects on github.
