### ISSUE TITLE
[Application] for my OSS Project

### ISSUE THREAD

**Issue by ARHAEEM** [gridaco/cors.sh#131]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [x] My project has more than **10 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://n8n.io/creators/nskha

### URL to your website

https://n8n.nskha.com

### Expected Quota of usage

~5000 maxmium.

### Details

```markdown
- Category: Automation
- License: MIT
- Date of release: multiples dates
```

### Anything else?

my automation libraries will be public on github.com/automations-project i didn't launch yet but you can see my activity verified and partnered with n8n here n8n.io/creators/nskha

**Comment by softmarshmallow** [comment]
Sorry. you need a public github repo for this application.
