### ISSUE TITLE
Order management software

### ISSUE THREAD

**Issue by duyquang1410** [gridaco/cors.sh#132]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project has more than **10 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://github.com/duyquang1410/acolorhome
https://github.com/duyquang1410/learning

### URL to your website

https://alphacolor.vn

### Expected Quota of usage

1,000,000 requests / month

### Details

```markdown
- Category: Laravel
- License: MIT
- Date of release: 06/10/2023
```

### Anything else?

I bought x-cors-api-key : live_8ebe515e65cb46801a6e76e10b0a65b621e11e64b4338fddea47620f5a2542d6
But now it's having an inactive error, I need it to work.

**Comment by softmarshmallow** [comment]
Hi. both your listed repo seems removed or private, not public and open-sourced
