### ISSUE TITLE
https://github.com/Rule-34/App

### ISSUE THREAD

**Issue by AlejandroAkbal** [gridaco/cors.sh#134]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project has more than **10 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://github.com/Rule-34/App

### URL to your website

https://r34.app/

### Expected Quota of usage

Don't really know until I've tried

Not every user needs a proxy, only the ones which their country has banned access

### Details

```markdown
- Category: Adult entertainment
- License: AGPL-3.0 license 
- Date of release: Sometime in 2020, don't remember sorry
```

**Comment by softmarshmallow** [comment]
Hi thank you for your application.
Although we will need a estimation. I guess you won't be able to a/b gate the user by region, which means every user will still hit the endpoint * resources. could be potentially a lot.

**Comment by AlejandroAkbal** [comment]
I currently have 38k unique visitors / day

But only 0.3% will need a proxy, all the others won't, even if this number is exaggerated to a 1%, it would be 114 users / day 

I think it could be very doable

What do you think @softmarshmallow

**Comment by softmarshmallow** [comment]
Can you make sure this is the right solution you are looking for? This is not a proxy for fooling geo ip, it won't work as you expect. This is a CORS proxy. 

Thanks :)

**Comment by AlejandroAkbal** [comment]
Yeah, I understand, my use case is both CORS and geo, and a proxy, if I'm not wrong does both, since it does the request for you, right?

Its exactly what I need

**Comment by softmarshmallow** [comment]
Let's continue our talk on Slack. I'd glad to be your sponsor. although, since it's a audult product I feel a bit concerned if your usage would exceed the estimated.

( would love to help, but if the usage grows, I might have to revoke this. )


Please join our slack channle https://grida.co/join-slack and reach me out with handle `universe`

Thanks : )
