### ISSUE TITLE
AD Compressor - Figma Plugin

### ISSUE THREAD

**Issue by weilinzung** [gridaco/cors.sh#141]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project has more than **10 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://www.figma.com/community/plugin/803370930903876544/ad-compressor

### URL to your website

https://www.figma.com/community/plugin/803370930903876544/ad-compressor

### Expected Quota of usage

- 20mb + per request if possible

- 1,000,000 requests / month (should be fine)
- Unlimited requests per hour (should be fine)
- No down time (should be fine)

### Details

```markdown
- Category: Figma Plugin
- License: https://www.figma.com/legal/community-free-resource-license/
- Date of release: January 30, 2020
```

### Anything else?

The Figma plugin is free for public use because it was developed during company hours. However, due to company policy, I can't share the source code.

Currently, I'm using [Railway](https://railway.app/) to host CORS Anywhere, which allows the plugin to access the TinyPNG API for image compression: [TinyPNG API](https://tinypng.com/third-party) => AD Compressor.

I'm looking for alternative solutions to manage this without incurring monthly costs.

**Comment by softmarshmallow** [comment]
Sorry, the project must be open in github in order to apply. 😢
