### ISSUE TITLE
OSS Program: BMK

### ISSUE THREAD

**Issue by DattatreyaReddy** [gridaco/cors.sh#145]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project has more than **10 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://github.com/DattatreyaReddy/bmk

### URL to your website

https://bmk.padya.in

### Expected Quota of usage

100/month

### Details

```markdown
- Category:Web Bookmark
- License:MPL-2.0
- Date of release: 08-12-2024
```

**Comment by softmarshmallow** [comment]
Hi. sorry, but your application does not comply with ` My project has more than 10 ⭐️stars on Github, which is the required for this program.`

Closing for now.
