### ISSUE TITLE
No CORS for rate limit error response

### ISSUE THREAD

**Issue by anonghuser** [gridaco/cors.sh#18]
When the rate limit is reached, you return a nice 429 response with headers indicating the limit and time till reset and all... but you don't include CORS headers so the origin site cannot read it. It is only visible in the devtools, not programmatically. It will be better if you add CORS headers to the error response so the caller can at least see its status code, and possibly even ratelimit headers.

**Comment by softmarshmallow** [comment]
I'm afraid that making a request after rate limit reached is not quite a way. The primary reason for having a rate limit is to save cost (aws cost) and to have a response of a target requires for us to run full api call, which we do not know how heavy the operation (how long the api response time) will be.
