### ISSUE TITLE
JSON to Figma Plugin

### ISSUE THREAD

**Issue by PavelLaptev** [gridaco/cors.sh#24]
Hi! There is a Figma plugin https://github.com/PavelLaptev/JSON-to-Figma, and I need to bypass CORS to fetch images.
Thanks!

**Comment by softmarshmallow** [comment]
Hi. Please leave your email to universe@grida.co

+ Is there any expected usage quota?

**Comment by PavelLaptev** [comment]
@softmarshmallow done! About the quota, it's hard to say right now, this is actually what I want to check. I assume it could be more than 5mb, but it shouldn't be a problem.

**Comment by PavelLaptev** [comment]
@softmarshmallow thanks! Just got my API token

**Comment by softmarshmallow** [comment]
@PavelLaptev 
No problem. I would very appreciate a small acknowledgment on your project's readme (details in email)

:) Cheers

**Comment by PavelLaptev** [comment]
@softmarshmallow sure thing. As soon as I update the plugin, I'll add it to the README :-)
