### ISSUE TITLE
wishlist (rust web application)

### ISSUE THREAD

**Issue by temportalflux** [gridaco/cors.sh#25]
I'm working on a serverless web app, which leverages github oauth2 for accounts. I'm using cors.sh to request access tokens on user login. https://github.com/temportalflux/wishlist

**Comment by softmarshmallow** [comment]
Hi. Can you email me so that I can send you an API Key?
Here is my email address. [universe@grida.co](mailto://universe@grida.co)

Thank you for applying. I Apologies for the late reply.
