### ISSUE TITLE
https://doobyeol.github.io/

### ISSUE THREAD

**Issue by doobyeol** [gridaco/cors.sh#26]
hi!
my personal portfolio [](https://doobyeol.github.io/) bypasses the CORS and brings personal blog posts.
thanks.

**Comment by softmarshmallow** [comment]
Hi. Can you email me so that I can send you an API Key?
Here is my email address. [universe@grida.co](mailto://universe@grida.co)

Thank you for applying.

**Comment by softmarshmallow** [comment]
Check your inbox. Thanks :)
