### ISSUE TITLE
apply for OSS Program for Astral

### ISSUE THREAD

**Issue by monlovesmango** [gridaco/cors.sh#30]
hey there,

I am creating a client on [nostr](https://github.com/nostr-protocol/nostr) and would like to apply for the OSS Program for a cors.sh plan. My client is [astral](https://github.com/monlovesmango/astral) and is MIT licensed. I need to fetch lightning invoices that return small json blobs, and most lightning services don't serve them with cors headers. In the future I might also use it to create link previews for user posted content.

Please let me know if you have any questions!

Thank you!
Mon

**Comment by softmarshmallow** [comment]
Hi. What an exciting project! Please send me an email (universe@grida.co) So I can guide you through further steps.

Thank you :)

**Comment by monlovesmango** [comment]
hey @softmarshmallow ! thank you so much for running this program, its really a great resource for OSS. kudos to you!

I actually ended up figuring out what was going wrong in my own (very simple) cors proxy server this morning so I don't think I need this service at this time, sorry I didn't close the issue earlier. 

thanks again!
mon
