### ISSUE TITLE
YorkURMP

### ISSUE THREAD

**Issue by mahfoozm** [gridaco/cors.sh#34]
### You are applying for OSS program

- [X] Yes my project is OSS licensed and open to public.

### Repository URL to your project

https://github.com/mahfoozm/YorkURMP

### Expected Quota of usage

expected 5000-10000 requests/month

### Details

```markdown
- Category: Education
- License: GPLv3
- Date of release: 01/04/2023
```

**Comment by softmarshmallow** [comment]
Hi. Just to confirm. You don't need it anymore?
