### ISSUE TITLE
Ourss podcast

### ISSUE THREAD

**Issue by jsmithdev** [gridaco/cors.sh#35]
### You are applying for OSS program

- [X] Yes my project is OSS licensed and open to public.

### Repository URL to your project

https://github.com/jsmithdev/ourss

### URL to your website

https://ourss.app

### Expected Quota of usage

<1000

### Details

```markdown
- Category: Podcast
- License: MIT
- Date of release: Apr 6, 2022
```

### Anything else?

It's an open source web app, with no real users yet, that checks rss feeds / podcasts. Most servers hosting podcasts work fine so it fetches normally first but falls back to a reverse proxy on (cors) error.

**Comment by softmarshmallow** [comment]
Hi. Thank you for your application. Seems like a cool project :)

Please email me with subject "cors.sh OSS - #<issue-id>" to [universe@grida.co](mailto:universe@grida.co).
I'll send you an api key on that thread.

Thank you and happy hacking

**Comment by jsmithdev** [comment]
Thanks for all softmarshmellow and cors.sh :)
