### ISSUE TITLE
cors.bridged.cc not working

### ISSUE THREAD

**Issue by kitzian** [gridaco/cors.sh#4]
**Describe the bug**
https://app.cors.bridged.cc/ isn’t working right now
**To Reproduce**
1. Go to https://app.cors.bridged.cc/
2. GET any website and click on Send
“Error: Network Error”
F12 console logs: https://pastebin.com/iE91rm04

**Expected behavior**
It should give a response.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
Cors always worked on my server and localhost, but it isn’t working anymore since yesterday. When I go to the website to send a test request, it keeps saying “Error: Network Error”

**Comment by softmarshmallow** [comment]
Please open a new issue if the problem still remains. closing due to `proxy.cors.sh` migration.
