### ISSUE TITLE
Cors.sh Apply for OSS Program

### ISSUE THREAD

**Issue by CSS-MB** [gridaco/cors.sh#40]
### You are applying for OSS program

- [X] Yes my project is OSS licensed and open to public.

### Repository URL to your project

https://github.com/CSS-MB/cssmbmaster.git

### Expected Quota of usage

Less than 100,000

**Comment by softmarshmallow** [comment]
Hi. Can you specify what your project does and why you need cors proxy for?
I've checked your repo and It's hard for me to understand what it does in specifics
Thank you :)

**Comment by softmarshmallow** [comment]
Hi. I'm sorry to tell this but Your application seems like more suitable with our Pro plan not OSS plan. You can purchase it from our website with $4/Mo.

The main reason is I don't see a clear benefit to the community and I'm still quite not sure what you are trying to build as an OSS.

Please re-open this issue if you have an appeal to make
Thank you.
