### ISSUE TITLE
Cors Project

### ISSUE THREAD

**Issue by xRoDriGox** [gridaco/cors.sh#42]
### You are applying for OSS program

- [X] Yes my project is OSS licensed and open to public.

### Repository URL to your project

https://github.com/xRoDriGox/ionic_xlead

### Expected Quota of usage

1.000.000 per month

### Details

```markdown
- Category:
- License:
- Date of release:
```

**Comment by softmarshmallow** [comment]
Hi. I found that your repo is empty. Please re-open this thread when your project is applicable.
Thank you
