### ISSUE TITLE
TT Site

### ISSUE THREAD

**Issue by graeme-michael-scott** [gridaco/cors.sh#44]
### You are applying for OSS program

- [X] Yes my project is OSS licensed and open to public.

### Repository URL to your project

https://github.com/graeme-michael-scott/TT-Site

### URL to your website

https://turkeytom.net/

### Expected Quota of usage

100-250 per day

### Details

```markdown
- Category: Website
- License: MIT
- Date of release: 01/31/23
```

### Anything else?

This is a website for the famous YouTuber Turkey Tom, and I will be using CORS to make API calls to collect youtube video info

https://www.youtube.com/channel/UCDKJdFer1phQI95UinPZehw

**Comment by softmarshmallow** [comment]
Hi. Have you considered using a paid Pro version? The site seems to be classified as commercial to my perspective.

Once we review the project's purpose to meet our community guidance, we'll send you an API Key. Otherwise, consider using a Pro version :)

**Comment by graeme-michael-scott** [comment]
My apologies, will do
