### ISSUE TITLE
dec-npk

### ISSUE THREAD

**Issue by avdeevskiy** [gridaco/cors.sh#46]
### You are applying for OSS program

- [X] Yes my project is OSS licensed and open to public.

### Repository URL to your project

https://github.com/ShparagaVladimir/GradebookProject

### URL to your website

dec-npk.srspu.ru

### Expected Quota of usage

100

### Details

```markdown
- Category:
- License:
- Date of release:
```

**Comment by softmarshmallow** [comment]
Hi. Please re-open this issue when your repository is publicly available.
Plus, please note that we are running this program for existing open source project, newly created projects may not comply.
