### ISSUE TITLE
Cors Fix

### ISSUE THREAD

**Issue by GMuthuraja** [gridaco/cors.sh#47]
### You are applying for OSS program

- [X] Yes my project is OSS licensed and open to public.

### Expected Quota of usage

<1K requests per month.

### Details

```markdown
- Category: Appointment Booking
- License: Open Source
- Date of release: Dec 2022
```

**Comment by softmarshmallow** [comment]
Hi. Sorry about the bad news, but we have a new policy: Minimum required of 5 stars for OSS projects. Otherwise it is considered as personal project.

I'm sorry to tell you this, but your application does not meet the requirements
