### ISSUE TITLE
Application for mukulpatnaik/researchgpt

### ISSUE THREAD

**Issue by mukulpatnaik** [gridaco/cors.sh#48]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project is has more than **5 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://github.com/mukulpatnaik/researchgpt

### URL to your website

https://researchgpt.ue.r.appspot.com/

### Expected Quota of usage

Not more than 100 a day

### Details

```markdown
- Category: Artificial Intelligence
- License: MIT
- Date of release: 2/14/2023
```

**Comment by softmarshmallow** [comment]
@mukulpatnaik Thank you for your application. Please send me an email with subject `CORS.SH OSS #48` so I can send you an API Key. 

Thank you :)

**Comment by mukulpatnaik** [comment]
Have sent an email to universe@grida.co. Thanks:)

**Comment by mukulpatnaik** [comment]
@softmarshmallow hi :) I'm still awaiting an api key, please let me know if you have sent it. thanks

**Comment by softmarshmallow** [comment]
Hi. I'm sorry 
Could you please tell me your email address ? cuz I don't see it in my inbox

Sorry about the delay.

**Comment by mukulpatnaik** [comment]
Hi it has been over a month and a half since I sent the email, please follow up. My address is mukulpatnaik@gmail.com

**Comment by mukulpatnaik** [comment]
@softmarshmallow

**Comment by softmarshmallow** [comment]
Hi @mukulpatnaik . let's talk in slack. It'd be faster
https://grida.co/join-slack

Sorry about the delay
