### ISSUE TITLE
Search Satellite Imagery

### ISSUE THREAD

**Issue by jo-chemla** [gridaco/cors.sh#49]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project is has more than **5 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://github.com/Iconem/search-satellite-imagery/

### URL to your website

https://iconem.com

### Expected Quota of usage

max 10000

### Details

```markdown
- Category: Earth Observation
- License: MIT
- Date of release: 01/01/2023
```

**Comment by softmarshmallow** [comment]
Hi. Please send me an email with `CORS.SH #49`. Let me give you an api key and instructions from there :)

**Comment by jo-chemla** [comment]
Thanks I did just that. 
Best,

**Comment by softmarshmallow** [comment]
Hi. Is it ok for me to close this thread?

**Comment by jo-chemla** [comment]
yes sure sorry
