### ISSUE TITLE
How do I cancel my account?

### ISSUE THREAD

**Issue by alita-moore** [gridaco/cors.sh#50]
How do I get invoices and or cancel my account?

**Comment by softmarshmallow** [comment]
Hi. You will receive invoices from stripe. ( if you haven't please let me know )

About the cancellation, please send an email to hello@grida.co with the email you've signed up with. We'll send you a customer portal link that you can manage the subscriptions. 😀 

Thank you.

**Comment by SetoKaiba** [comment]
I've sent a email. I'd like to have a customer portal link to manage subscriptions as well. @softmarshmallow

**Comment by softmarshmallow** [comment]
@SetoKaiba Hi. Email sent. Also on slack as well :)

**Comment by SetoKaiba** [comment]
Thank you. I got it.
