### ISSUE TITLE
Deimos

### ISSUE THREAD

**Issue by Zoronium** [gridaco/cors.sh#52]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project is has more than **5 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://github.com/Zoronium/Deimos-Backend

### URL to your website

https://Deimos-backend.zoronium.repl.co

### Expected Quota of usage

1000

### Details

```markdown
- Category: Web
- License:MIT
- Date of release:05/03/2023
```

### Anything else?

please see our readme file at https://github.com/Zoronium/Deimos-Backend

**Comment by softmarshmallow** [comment]
Sorry. Your project does not meet the minimum requirements. 🙏
