### ISSUE TITLE
USD/VES Monitor

### ISSUE THREAD

**Issue by alejandroch1202** [gridaco/cors.sh#53]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project is has more than **5 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://github.com/alejandroch1202/dollar-monitor

### URL to your website

https://monitordolar.netlify.app/

### Expected Quota of usage

- Less than 1,000,000 requests / month
- Less than 5mb per request 

### Details

```markdown
- Category: Educational / Utils
- License: MIT
- Date of release: 03/26/2023
```

### Anything else?

Although my app was made for practice / educational purposes, here in my country there is an official rate of USD to our national currency ([BCV](https://www.bcv.org.ve/)), however, the "street" price often is a quite different, so, people sometimes needs to check that price in order to make deals and it would be nice keep this page working for a small group of people that I share.

**Comment by softmarshmallow** [comment]
Hi. I'm sorry to let you know that your application does not meet the 5-star requirements.
Please let me know if there is any changes or you can always use the Paid Pro version.
Thank you.

**Comment by alejandroch1202** [comment]
Hi @softmarshmallow, I just got my five starts. I'm ready!

**Comment by alejandroch1202** [comment]
@softmarshmallow Shoul I open a new issue or will this one work?
