### ISSUE TITLE
Access Origin Issue

### ISSUE THREAD

**Issue by GodCrypto0616** [gridaco/cors.sh#54]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project is has more than **5 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://github.com/BoredMemes/BoredMemes-Frontend

### Expected Quota of usage

I expect less than 100,000 api calls

### Details

```markdown
- Category:
- License:
- Date of release:
```

**Comment by softmarshmallow** [comment]
Hi. Please re-open this issue after the project meets the requirements. Thank you
