### ISSUE TITLE
OS Project Application: Algo

### ISSUE THREAD

**Issue by IMGROOT2** [gridaco/cors.sh#55]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project is has more than **5 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://github.com/IMGROOT2/algo

### URL to your website

https://algo-usaco.web.app/

### Expected Quota of usage

Currently, not more than 500 per month, but potential max of 10k per month if my website becomes more popular.

### Details

```markdown
- Category: Web App
- License: MPL-2.0
- Date of release: 4/3/2023
```

### Anything else?

I have 5 stars, not more than 5, but hopefully, it still suffices :)

**Comment by softmarshmallow** [comment]
Hi. thank you for your application. Please reach me out on our slack channel - https://grida.co/join-slack You can find me with handle `@universe`

**Comment by IMGROOT2** [comment]
Alright, thanks! I mentioned you in #general.
