### ISSUE TITLE
OpenChat

### ISSUE THREAD

**Issue by julianjelfs** [gridaco/cors.sh#67]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project is has more than **5 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://github.com/open-chat-labs/open-chat

### URL to your website

https://oc.app

### Expected Quota of usage

< 1000 per day. 

### Details

```markdown
- Category: Chat Platform
- License: GNU AFFERO GENERAL PUBLIC LICENSE
- Date of release: March 2023
```

### Anything else?

OpenChat is a chat / communications platform running on The Internet Computer. The project is open source and is governed by a DAO.

**Comment by softmarshmallow** [comment]
Hi. May I ask where exactly the proxy will take place? Since your project is a "chat" app, If it's somehow used for the messaging part, it seems quite intensive. else, if it is just for some part from your website (landingpage) to obtain certain data, we can consider this plan. Thank you :)

**Comment by julianjelfs** [comment]
Hi - it will be used for rendering previews of links within chat messages. 

So here is an example of what a chat message with an expanded link preview would look like. 

<img width="814" alt="image" src="https://github.com/gridaco/cors.sh/assets/86620/cf673e7d-f683-4367-ac3d-18cb9f71d98c">

**Comment by julianjelfs** [comment]
Not all messages will contain links, not all links will be "expanded" with the preview. We also handle twitter and youtube links differently and they are probably the most commonly used link types.

**Comment by softmarshmallow** [comment]
Great. thanks for the details. Although, I believe what you are looking for is custom Enterprise plan, not OSS program. As your service grow, I don't think we'de be able to serve in sustainable. Are you open to this or have second though?

**Comment by julianjelfs** [comment]
No of course that's fair enough. I have already subscribed to the pro plan actually and it's running on live and working fine. I think we will evaluate for a while and see if it works ok for us or if the limit is a problem in any way. I will get back to you if we want or need to upgrade. Thanks.

**Comment by softmarshmallow** [comment]
Great! Feel free to re-open this issue when then. Plus you know how to reach me on Slack. Have a nice one :)
