### ISSUE TITLE
Duck Address Send OSS Program Application

### ISSUE THREAD

**Issue by Hamster45105** [gridaco/cors.sh#68]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project is has more than **5 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://github.com/Hamster45105/DuckAddressSend

### URL to your website

https://hamster45105.github.io/DuckAddressSend/

### Expected Quota of usage

Not sure, depends on how many people use the site once the features that require cors.sh actually are working.

### Details

```markdown
- Category: Website
- License: MIT
- Date of release: 27/07/2023
```

### Anything else?

Haven’t got 5 stars yet due to the fact that this project is new. Some features will not currently work unless I can implement cors.sh (attempted to use other cors-anywhere, however not working as expected.

**Comment by softmarshmallow** [comment]
Hi. Sorry to let you know that your project does not meet our minimum 5-star requirements.
Please re-apply as your project grows. Thank you for your kind understanding
