### ISSUE TITLE
FFO Application: My-LOL-MMR

### ISSUE THREAD

**Issue by ymh0951** [gridaco/cors.sh#8]
I developed a mmr search site as a toy project.
However, 429 errors appear because the API request amount is limited.
github: https://github.com/ymh0951/My-LOL-MMR

**Comment by softmarshmallow** [comment]
Hey. Thank you for your submission. I'll take a look and get back to you within few days. Before we continue, can you kindly answer below questions?  

- Is the site currently online? If so, please provide the address to it. 
- Are you getting 429 from your live website or from local dev environment?
-Is your project using the legacy cors.bridged.cc ? (It recently migrated to Cors.sh)
- How many users do you have and what is the estimated requests per month? (Not per user, but throughout the entire site)

Thank you. :)
지원해 주셔서 감사합니다.

**Comment by ymh0951** [comment]
1. Is the site currently online? If so, please provide the address to it.

* github: https://github.com/ymh0951/My-LOL-MMR
* website: https://ymh0951.github.io/My-LOL-MMR

2. Are you getting 429 from your live website or from local dev environment?
-Is your project using the legacy cors.bridged.cc ? (It recently migrated to Cors.sh)

*  I'm communicating with Axios.
The api is used by 'What is my mmr?'

3. How many users do you have and what is the estimated requests per month? (Not per user, but throughout the entire site)
* It's just been developed, so there aren't many users.
The amount of api requests provided by 'LOL' is limited to 60 per minute
