### ISSUE TITLE
corskilla

### ISSUE THREAD

**Issue by Gabriel12548891** [gridaco/cors.sh#86]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project is has more than **5 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://github.com/Gabriel12548891/cors-anywhere

### Expected Quota of usage

5654

### Details

```markdown
- Category:
- License:
- Date of release:
```

**Comment by softmarshmallow** [comment]
Sorry to let you know that your repo does not meet the requirements.
