### ISSUE TITLE
I want to apply this program for my open source repository: reactjs-social-login

### ISSUE THREAD

**Issue by cuongdevjs** [gridaco/cors.sh#91]
### You are applying for validated OSS program

- [X] My project is OSS licensed and open to public. (Must have LICENSE file)
- [X] My project has more than **5 ⭐️stars** on Github, which is the required for this program.

### Repository URL to your project

https://github.com/cuongdevjs/reactjs-social-login

### URL to your website

https://react-social-login.netlify.app/

### Expected Quota of usage

100000 request per month

### Details

```markdown
- Category: Login Social
- License: MIT
- Date of release: 27/08/2023
```

**Comment by softmarshmallow** [comment]
Hi. Thank you for your submission. Will your demo site will be using the api? Or will it be shipped as part of your sdk?

Where exactly would the cors proxy apply to?

Thank you :)

**Comment by cuongdevjs** [comment]
Hi, thanks for your prompt reply. You can check on my demo site, it using the API key at the moment and unfortunately, the API has exceeded the quota.

For example, you can try with Linkedin provider, please open devtool to see the error

**Comment by cuongdevjs** [comment]
Hi, Can you respond to this for me?

**Comment by cuongdevjs** [comment]
any news, please @softmarshmallow?
